[project]
name = "ansible-common-roles"
version = "1.3.0"
description = "Ansible roles that are shared across project specific roles"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ansible-dev-tools>=25.8.3",
]
