galaxy_info:
  author: Johnny Knighten
  description: Disable a user account and remove their SSH access
  company: Homelab
  license: Apache-2.0
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
