---
apt_nexus_mirror_nexus_base_url: "nexus.example.com"

apt_nexus_mirror_ubuntu_nexus_sources:
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/ubuntu-jammy-proxy/ jammy main restricted"
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/ubuntu-jammy-proxy/ jammy-updates main restricted"
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/ubuntu-jammy-proxy/ jammy universe"
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/ubuntu-jammy-proxy/ jammy-updates universe"
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/ubuntu-jammy-proxy/ jammy multiverse"
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/ubuntu-jammy-proxy/ jammy-updates multiverse"
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/ubuntu-jammy-proxy/ jammy-backports main restricted universe multiverse"
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/ubuntu-jammy-proxy/ jammy-security main restricted"
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/ubuntu-jammy-proxy/ jammy-security universe"
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/ubuntu-jammy-proxy/ jammy-security multiverse"

apt_nexus_mirror_debian_nexus_sources:
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/debian-security-proxy/ bookworm-security main"
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/debian-bookworm-proxy/ bookworm main"
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/debian-bookworm-proxy/ bookworm-updates main"
  - "deb http://{{ apt_nexus_mirror_nexus_base_url }}/repository/debian-bookworm-proxy/ bookworm-backports main"

apt_nexus_mirror_nexus_sources: "{{ (
  apt_nexus_mirror_ubuntu_nexus_sources if ansible_distribution == 'Ubuntu' else
  apt_nexus_mirror_debian_nexus_sources if ansible_distribution == 'Debian' else
  []
) }}"
