galaxy_info:
  author: Johnny Knighten
  description: Sets up PIP to use Nexus PyPi mirror (Debian/Ubuntu)
  company: Homelab
  license: Apache-2.0
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
    - name: Debian
      versions:
        - bookworm
